# Use the official, lightweight Nginx image
FROM nginx:stable-alpine

# Copy the single index.html file to the Nginx web server directory
COPY index.html /usr/share/nginx/html

# Expose port 80, which is the default port for Nginx
EXPOSE 80