services:
  backend:
    build: ./Backend
    ports:
      - "5001:5000"
    volumes:
      - faiss_data:/app/faiss_index
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  frontend:
    build: ./Frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  faiss_data: