# In docker-compose.yml

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - faiss_data:/app/faiss_index
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

# This defines the named volume used by the backend service
volumes:
  faiss_data: