# In .github/workflows/ci.yml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          # Use the correct case for the directory name
          pip install -r Backend/requirements.txt